import Navbar from "@/comps/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Phudu } from "next/font/google";
import Footer from "@/comps/footer/Footer";

const phudu = Phudu({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={phudu.className}>
        <div className="min-h-screen max-w-7xl mx-auto flex flex-col items-center justify-between">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
